#ifndef STITCH_TUTOR_TEXT_H
#define STITCH_TUTOR_TEXT_H

const char *tutor_text[] = {
"",
"===============================================================================",
"=                                                                             =",
"=                         S T I T C H   T U T O R                             =",
"=                                                                             =",
"=                    A Gentle Introduction to Modal Editing                    =",
"=                                                                             =",
"===============================================================================",
"",
"  Welcome to the Stitch Tutor!",
"",
"  Stitch is a minimal, modal text editor. It is designed to be gentle",
"  enough for beginners, yet powerful enough for daily work.",
"",
"  This tutorial is loaded into a scratch buffer. You can freely edit,",
"  delete, and rearrange this text to practice. None of your actual files",
"  will be affected. When you are done, type  :q  or  :q!  to return",
"  to your previous file.",
"",
"  Estimated time: 10-15 minutes.",
"",
"  NOTE: Throughout this tutorial, commands are shown in single quotes",
"  like 'x'. Do not type the quotes themselves, only the key inside.",
"",
"",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"  Lesson 1: UNDERSTANDING MODES",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"",
"  Stitch has four modes. You are currently in NORMAL mode.",
"",
"    NORMAL   --  Navigate text, issue commands. (This is the default.)",
"    INSERT   --  Type text into the buffer.",
"    VISUAL   --  Select blocks of text to act on.",
"    COMMAND  --  Execute editor commands (save, quit, etc.).",
"",
"  The current mode is always displayed in the bottom-left status bar.",
"  Press <ESC> at any time to return to NORMAL mode from any other mode.",
"",
"",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"  Lesson 2: MOVING THE CURSOR",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"",
"  In Normal mode, you can move the cursor with Arrow Keys or with:",
"",
"                k           (up)",
"            h       l       (left / right)",
"                j           (down)",
"",
"  Try moving around this paragraph now to get comfortable.",
"",
"  ---",
"",
"  2.1  WORD JUMPING",
"",
"  Moving character-by-character is slow. Use these to jump faster:",
"",
"    'w'   --  Jump forward to the start of the next word.",
"    'b'   --  Jump backward to the start of the previous word.",
"",
"  Practice on this line:  apple banana cherry date elderberry fig grape",
"",
"  ---",
"",
"  2.2  FIND CHARACTER",
"",
"    'f'   --  Find character. Press 'f' then any character to jump",
"              to the next occurrence of that character on the line.",
"",
"  Try it: press  f  then  z  on this line to jump to ---> z <--- there.",
"",
"  ---",
"",
"  2.3  LINE JUMPING",
"",
"    '0'   --  Jump to the beginning of the current line.",
"    '$'   --  Jump to the end of the current line.",
"",
"  Try pressing '0' now, then '$', to ping-pong across this line.",
"",
"  ---",
"",
"  2.4  FILE JUMPING",
"",
"    'g'   --  Jump to the very first line of the file.",
"    'G'   --  Jump to the very last line of the file.",
"",
"  Try pressing 'G' now. Then press 'g' to come back to the top.",
"",
"  ---",
"",
"  2.5  PAGE SCROLLING",
"",
"    Page Up    --  Scroll one full screen up.",
"    Page Down  --  Scroll one full screen down.",
"",
"",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"  Lesson 3: ENTERING INSERT MODE",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"",
"  To type text, you must enter INSERT mode. There are several ways:",
"",
"    'i'   --  Insert before the cursor.",
"    'a'   --  Append after the cursor.",
"    'I'   --  Insert at the first non-whitespace character of the line.",
"    'A'   --  Append at the end of the line.",
"    'o'   --  Open a new blank line BELOW and enter Insert mode.",
"    'O'   --  Open a new blank line ABOVE and enter Insert mode.",
"",
"  Always press <ESC> when you are done typing to return to Normal mode.",
"",
"  ---",
"",
"  Exercise 3.1:  Move your cursor to the gap below and press 'i'.",
"                 Type the word  great  and press <ESC>.",
"",
"  --> Stitch is a _____ editor.",
"",
"  ---",
"",
"  Exercise 3.2:  Move to the line below. Press 'A' to append at the end.",
"                 Type some text, then press <ESC>.",
"",
"  --> I need more words here",
"",
"  ---",
"",
"  Exercise 3.3:  Move to the line below. Press 'I' to jump to the start",
"                 of the line content and enter Insert mode.",
"",
"      --> (your cursor should jump here, before the arrow)",
"",
"  ---",
"",
"  Exercise 3.4:  Press 'o' to open a new line below this one.",
"                 Type anything, then press <ESC>.",
"",
"",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"  Lesson 4: DELETING TEXT",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"",
"  4.1  SINGLE CHARACTER DELETION",
"",
"    'x'   --  Delete the character under the cursor.",
"",
"  Exercise:  Move the cursor to each 'Z' below and press 'x'.",
"",
"  --> The coZZZw jumped over the moZZon.",
"",
"  ---",
"",
"  4.2  DELETE ENTIRE LINE",
"",
"    'dd'  --  Delete the entire current line. (Press 'd' twice.)",
"",
"  Exercise:  Move to the line below and press 'dd'.",
"",
"  --> DELETE THIS ENTIRE LINE. IT SHOULD NOT EXIST.",
"",
"  ---",
"",
"  4.3  DELETE TO END OF LINE",
"",
"    'D'   --  Delete from the cursor to the end of the line.",
"",
"  Exercise:  Place your cursor on the 'X' below and press 'D'.",
"",
"  --> Keep this part. XXXXXXX Delete this part.",
"",
"  ---",
"",
"  4.4  CHANGE CHARACTER",
"",
"    'c'   --  Delete the character under the cursor and enter Insert mode.",
"              (Like 'x' but drops you straight into typing.)",
"",
"  Exercise:  Move to the 'Q' below, press 'c', type 's', press <ESC>.",
"",
"  --> The Qun is shining.",
"",
"  ---",
"",
"  4.5  CHANGE TO END OF LINE",
"",
"    'C'   --  Delete from cursor to end of line, then enter Insert mode.",
"              (Like 'D' but drops you straight into typing.)",
"",
"  Exercise:  Move to the 'X' below, press 'C', type 'the lazy dog.',",
"             then press <ESC>.",
"",
"  --> The quick brown fox jumped over XXXXXXXXXXXXXXXXX",
"",
"",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"  Lesson 5: UNDO AND REDO",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"",
"    'u'   --  Undo the last change.",
"    'U'   --  Redo the last undone change.",
"",
"  Stitch groups related edits together intelligently. Typing a whole",
"  word and then pressing <ESC> counts as one undo step, not one per",
"  character.",
"",
"  Exercise:  Delete the line below with 'dd'. Then press 'u' to bring",
"             it back. Then press 'U' to delete it again.",
"",
"  --> This line is a yo-yo. Delete me, undo me, redo me.",
"",
"",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"  Lesson 6: VISUAL MODE  --  Select, Then Act",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"",
"  Visual mode is the heart of Stitch's editing philosophy.",
"  Instead of memorizing invisible Vim combinations like  diw  or  d$,",
"  you first SELECT what you want to change, then ACT on it.",
"",
"    'v'   --  Enter Visual mode. A highlight follows your cursor.",
"    <ESC> --  Cancel the selection and return to Normal mode.",
"",
"  Once you have a selection highlighted, you can act on it:",
"",
"    'd'   --  Delete the selected text.",
"    'x'   --  Delete the selected text. (Same as 'd'.)",
"    'c'   --  Change: delete the selection and enter Insert mode.",
"    'y'   --  Yank (copy) the selection to the clipboard.",
"    '>'   --  Indent the selected lines (adds 4 spaces).",
"    '<'   --  Outdent the selected lines (removes up to 4 spaces).",
"    '%'   --  Select the entire file.",
"",
"  ---",
"",
"  Exercise 6.1:  DELETING A VISUAL SELECTION",
"",
"  1. Move your cursor to the 'D' of 'DELETE_ME' below.",
"  2. Press 'v' to enter Visual mode.",
"  3. Press 'w' to extend the selection over the word.",
"  4. Press 'd' to delete it.",
"",
"  --> Please DELETE_ME from this sentence carefully.",
"",
"  ---",
"",
"  Exercise 6.2:  CHANGING A VISUAL SELECTION",
"",
"  1. Move to the 'R' of 'REPLACE_ME' below.",
"  2. Press 'v', then press 'w' to highlight it.",
"  3. Press 'c'. The selection is deleted and you enter Insert mode.",
"  4. Type  beautiful  and press <ESC>.",
"",
"  --> Stitch is a REPLACE_ME editor.",
"",
"  ---",
"",
"  Exercise 6.3:  INDENTING CODE",
"",
"  1. Move to the first line of the code block below.",
"  2. Press 'v', then 'j' twice to select all three lines.",
"  3. Press '>' to indent them.",
"  4. Press 'u' to undo if you want to try again.",
"",
"  --> function hello() {",
"  -->     return 42;",
"  --> }",
"",
"",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"  Lesson 7: YANK (COPY) AND PASTE",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"",
"  7.1  YANK A WHOLE LINE",
"",
"    'yy'  --  Yank (copy) the entire current line.",
"    'p'   --  Paste the clipboard after the cursor.",
"",
"  Exercise:  Move to the line below, press 'yy'. Then move to the",
"             empty line and press 'p'.",
"",
"  --> Copy this line.",
"",
"  (paste it here)",
"",
"  ---",
"",
"  7.2  YANK A VISUAL SELECTION",
"",
"  1. Move to the word 'sunshine' below.",
"  2. Press 'v', then 'w' to highlight it.",
"  3. Press 'y' to yank the selection.",
"  4. Move somewhere else and press 'p' to paste it.",
"",
"  --> The sunshine is warm today.",
"",
"",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"  Lesson 8: THE COMMAND PROMPT",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"",
"  Press ':' to open the command prompt at the bottom of the screen.",
"  Type a command and press ENTER to execute it. Press <ESC> to cancel.",
"",
"  SAVING AND QUITTING",
"",
"    :w          --  Save (write) the current file.",
"    :q          --  Quit. Warns if there are unsaved changes.",
"    :q!         --  Force quit without saving.",
"    :wq         --  Save and quit.",
"",
"  FILE OPERATIONS",
"",
"    :e <file>   --  Open a different file.",
"",
"  LINE NUMBERS",
"",
"    :nu         --  Turn on line numbers.  (Also: :number)",
"    :nonu       --  Turn off line numbers. (Also: :nonumber)",
"",
"  Exercise:  Type  :nu  now to turn on line numbers. Then  :nonu  to",
"             turn them off.",
"",
"  ---",
"",
"  JUMPING TO A LINE",
"",
"    :<number>   --  Jump to that line number.",
"",
"  Exercise:  Type  :1  to jump to the very first line of this tutorial.",
"             Then type  :200  to come back near here.",
"",
"  ---",
"",
"  SEARCH AND REPLACE",
"",
"    /           --  Open the search prompt. (Normal mode, not command.)",
"                    Use Left/Right arrows to cycle through matches.",
"                    Press <ESC> to cancel.",
"",
"    :s/old/new/ --  Replace the first occurrence of 'old' with 'new'",
"                    on the current line.",
"",
"  Exercise:  Move to the line below and type  :s/dog/cat/",
"",
"  --> The dog sat on the mat.",
"",
"  ---",
"",
"  SHELL COMMANDS",
"",
"    :!<cmd>     --  Run a shell command in the background.",
"                    Example:  :!ls",
"",
"  HELP",
"",
"    :h          --  Open this tutorial. (Also: :help, :tutor)",
"",
"  COMMAND HISTORY",
"",
"    While the command prompt is open, press Arrow Up / Arrow Down",
"    to cycle through your last 10 commands.",
"",
"",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"  Lesson 9: SEARCH",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"",
"  Press '/' in Normal mode to start an incremental search.",
"",
"  1. Type your search term. Matches highlight as you type.",
"  2. Press Left/Right arrows to jump between matches.",
"  3. Press ENTER or <ESC> to accept the position and close search.",
"",
"  Exercise:  Press '/' and type  apple  to find it in the line below.",
"",
"  --> I have an apple, a banana, another apple, and an orange.",
"",
"",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"  Lesson 10: BRACKET MATCHING",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"",
"  Stitch automatically highlights matching brackets in real-time:",
"",
"    ( )    [ ]    { }",
"",
"  Move your cursor onto any bracket below to see its partner light up.",
"",
"  --> function greet(name) { return [\"Hello\", name].join(\" \"); }",
"",
"",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"  Lesson 11: MOUSE SUPPORT",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"",
"  You can click anywhere in the text area to move your cursor there.",
"  This works in Normal mode and is great for quick repositioning.",
"",
"",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"  QUICK REFERENCE CARD",
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
"",
"  MOVEMENT                        EDITING",
"  h j k l   -- Cursor movement    i   -- Insert before cursor",
"  w         -- Next word           a   -- Append after cursor",
"  b         -- Previous word       I   -- Insert at line start",
"  f<char>   -- Find char on line   A   -- Append at line end",
"  0         -- Line start          o   -- New line below",
"  $         -- Line end            O   -- New line above",
"  g         -- File start          x   -- Delete character",
"  G         -- File end            c   -- Change character",
"  Page keys -- Scroll pages        dd  -- Delete line",
"                                   D   -- Delete to end of line",
"  VISUAL MODE                      C   -- Change to end of line",
"  v         -- Start selection     yy  -- Yank line",
"  d / x     -- Delete selection    p   -- Paste",
"  c         -- Change selection    u   -- Undo",
"  y         -- Yank selection      U   -- Redo",
"  > / <     -- Indent / Outdent",
"  %         -- Select all          COMMAND PROMPT",
"                                   :w        -- Save",
"  SEARCH                           :q        -- Quit",
"  /         -- Search              :q!       -- Force quit",
"  Left/Right -- Cycle matches      :wq       -- Save & quit",
"                                   :nu/:nonu -- Line numbers",
"                                   :<num>    -- Jump to line",
"                                   :s/a/b/   -- Substitute",
"                                   :e <file> -- Open file",
"                                   :!<cmd>   -- Shell command",
"                                   :h        -- This tutorial",
"",
"===============================================================================",
"",
"  Congratulations! You have completed the Stitch Tutor.",
"",
"  Stitch is designed to be gentle. You don't need to memorize every",
"  command at once. Start with  i, <ESC>, :w, :q  and build from there.",
"",
"  Type  :q  to return to your file.",
"",
"===============================================================================",
NULL
};

#endif
